services:
  database:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  bot:
    build:
      context: .
      dockerfile: dev.Dockerfile
      args:
        DATABASE_URL: postgres://postgres:postgres@database:5432/postgres
    restart: unless-stopped
    ports:
      - "3000:8000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@database:5432/postgres
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - "./src:/app/src"